govuk-one-login/simulator

LICENCE

ATO-746: Generate LICENCE file

---

.github/workflows/publish-image.yml

- Auto tagging on push to main (according to [discovery](https://docs.google.com/document/d/1u-xKH3b19CdA4XTpeKAGM53clWtdHL0kJYmN-uE3dKc/edit))
- Check that package release and tags follow agreed formatting

ATO-753: Set up pipeline to deploy to GitHub container registry

---

src/components/config/config-controller.ts
src/components/config/tests/config-controller.test.ts
src/config.ts
src/types/client-configuration.ts
src/types/config-request.ts
src/types/response-configuration.ts

to make the client and request config have a more clear, nested structure

BAU: Refactor config

---

src/app.ts
src/components/token/helper/key-helpers.ts
src/components/user-info/user-info-controller.ts
src/constants.ts
src/errors/user-info-request-error.ts
src/parse/parse-token-request.ts
src/types/user-info.ts
src/validators/signed-jwt-validator.ts
src/validators/user-info-request-validator.ts
tests/integration/user-info.test.ts

ATO-885: Add User Info Endpoint

---

src/components/config/config-controller.ts
src/components/config/tests/config-controller.test.ts
src/components/token/helper/create-access-token.ts
src/components/token/helper/create-id-token.ts
src/components/token/tests/helper/create-access-token.test.ts
src/components/token/tests/helper/create-id-token.test.ts
src/config.ts
src/constants.ts
src/parse/parse-token-request.ts
src/parse/tests/parse-token-request.test.ts
src/validators/signed-jwt-validator.ts
tests/integration/token.test.ts
tests/integration/user-info.test.ts

An RP might want to host the simulator elsewhere, but there are places that need to expose the URL - make this a config value

BAU: Configurable simulator url

---

src/components/config/config-controller.ts
src/parse/parse-token-request.ts
src/validators/id-token-error.ts

Allow PS signing keys
Remove slash on import
Reset authorise errors on config call with no errors

BAU: Demo fixes

---

README.md
docker-compose.yml
src/components/config/tests/config-controller.test.ts
src/components/token/tests/helper/create-access-token.test.ts
src/components/token/tests/helper/create-id-token.test.ts
src/config.ts
src/parse/tests/parse-token-request.test.ts
tests/integration/openid-configuration.test.ts
tests/integration/token.test.ts
tests/integration/trustmark.test.ts
tests/integration/user-info.test.ts

This allows docker to communicate over localhost

BAU: Set up docker network host mode

---

README.md

Updates README to include more information about the configurable fields for the simulator.

BAU: Updates README

---

src/components/user-info/user-info-controller.ts
src/types/user-info.ts
src/validators/user-info-request-validator.ts

We were returning all scopes for all requests

BAU: Only return requested scopes

---

src/components/user-info/user-info-controller.ts

This mimics the behaviour of the real system

BAU: Do not return phone number if empty string

---

src/components/logout/logout-controller.ts
tests/integration/logout.test.ts

The value now matches the one in integration

BAU: Fix default post logout url

---

src/components/user-info/user-info-controller.ts

This was returning empty string

BAU: We don't want phone number to be returned if it's falsy

---

.github/workflows/pre-merge-and-main-checks.yml

Sonarcloud action is being deprecated

ATO-1448: Migrate sonarcloud action to sonarqube

---

src/components/token/helper/key-helpers.ts
tests/integration/jwks.test.ts

This matches our actual JWKs endpoint

BAU: Add alg to jwks endpoint

---

src/components/openid-configuration/openid-configuration-controller.ts
tests/integration/openid-configuration.test.ts

Update open id config spec to include code_challenge_methods_supported: [S256]

ATO-1379: update open id config spec to include code_challenge_methods_supported: [S256]

---

src/components/authorise/authorise-get-controller.ts
src/components/token/helper/code-challenge-comparer.ts
src/components/token/token-controller.ts
src/parse/parse-auth-request.ts
src/parse/parse-token-request.ts
src/parse/tests/parse-token-request.test.ts
src/types/auth-request-parameters.ts
src/types/token-request.ts
tests/integration/token-controller.test.ts

Add PKCE verification to /token endpoint.

ATO-1379 support pkce at token endpoint

---

README.md

BAU: Fix broken "default configuration values" link

---

src/app.ts

This makes it more obvious that the simulator is working

BAU: Change the text served from the root page

---

src/validators/validate-auth-request-object.ts
src/validators/validate-auth-request-query-params.ts
tests/integration/app.test.ts

Matches: https://github.com/govuk-one-login/authentication-api/pull/6310

BAU: move response_mode validation earlier

---

src/components/authorise/authorise-get-controller.ts
src/parse/parse-auth-request.ts
src/utils/utils.ts
src/validators/tests/validate-auth-request-object.test.ts
src/validators/validate-auth-request-object.ts
tests/integration/authorise-get-controller.test.ts

As part of the login_hint work, the parses login_hint (from request object only) and passes it on to auth.

ATO-1632: add login_hint

---

src/parse/parse-token-request.ts
src/parse/tests/parse-token-request.test.ts

Matches: https://github.com/govuk-one-login/authentication-api/pull/6599

ATO-1684: Return error if empty auth code string

---

tests/acceptance/pages/base-page.js

Bump the test timeout to 30 seconds on the base page

BAU: Bump base timeout

---

.github/workflows/pre-merge-and-main-checks.yml

Bumps Sonar scan action to v5.3.1

BAU: Bump sonar scan action
