govuk-one-login/simulator

package-lock.json, package.json, src/app.ts, src/components/token/helper/create-access-token.ts, src/components/token/helper/create-id-token.ts, src/components/token/helper/key-helpers.ts, src/components/token/helper/sign-token.ts, src/components/token/tests/helper/create-access-token.test.ts, src/components/token/tests/helper/create-id-token.test.ts, src/components/token/token-controller.ts, src/config.ts, src/constants.ts, src/errors/parse-request-error.ts, src/errors/token-request-error.ts, src/parse/parse-token-request.ts, src/parse/tests/parse-token-request.test.ts, src/types/access-token-claims.ts, src/types/auth-request-parameters.ts, src/types/id-token-claims.ts, src/types/private-key-jwt.ts, src/types/token-request.ts, tests/integration/token.test.ts
- The simulator now has a `/token` endpoint. 
- This endpoint responds with a token response containing an access_token and an id_token  for a valid token request
- This includes:
- Validating the token request has all params for a `private_key_jwt` request
- Parsing and validating the client assertion 
- Creating and signing the Id and Access tokens
- Uses the Config class and the authCodeStore to get specific claim values where needed
- Returning an `error` and `error_description` for error states
- Code review commit by commit 
- Look at the tests in `tests/integration/token.test.ts` to see what the endpoint response is for a range of invalid requests
=> ATO-933: Generate access token

src/app.ts, src/components/authorise/authorise-get-controller.ts, src/components/authorise/tests/authorise-get-controller.test.ts, src/components/config/tests/config-controller.test.ts, src/components/token/tests/helper/create-id-token.test.ts, src/components/token/token-controller.ts, src/config.ts, src/constants.ts, src/errors/authorise-request-error.ts, src/errors/bad-request-error.ts, src/errors/missing-parameter-error.ts, src/errors/parse-auth-request-error.ts, src/errors/parse-token-request-error.ts, src/middleware/dedupe-query-params.ts, src/middleware/tests/dedupe-query-params.test.ts, src/parse/parse-auth-request-query-params.ts, src/parse/parse-token-request.ts, src/parse/tests/parse-auth-request-query-params.test.ts, src/parse/tests/parse-token-request.test.ts, src/types/auth-request-parameters.ts, src/types/vector-of-trust.ts, src/validators/claims-validator.ts, src/validators/scope-validator.ts, src/validators/tests/claims-validator.test.ts, src/validators/tests/scope-validator.test.ts, src/validators/tests/vtr-validator.test.ts, src/validators/vtr-validator.ts, tests/integration/app.test.ts, tests/integration/token.test.ts
- The simulator now has a `/authorize` endpoint. 
- This responds with a redirect to the valid redirect_uri with a fixed authcode 
- The code and parameters are stored in the AuthCode param store
- The `/authorize` request is parsed and validated against the client config and valid OIDC values
- 
- Code review commit by commit 
- Look at the tests in `authorise/tests/authorise-get-controller.test.ts` to see the outward API responses for a range of valid and invalid requests
=> ATO-827: Authorize endpoint

src/components/authorise/authorise-get-controller.ts, src/components/authorise/tests/authorise-get-controller.test.ts
Rather than hard-coding a value, generate a pseudorandom 32-byte Authorization Code and base-64 URL encode it
=> ATO-883: Generate auth code dynamically rather than hard-coding it

src/components/token/helper/create-access-token.ts, src/components/token/tests/helper/create-access-token.test.ts, src/components/token/token-controller.ts, src/types/access-token-claims.ts, tests/integration/token.test.ts
Adds: 
- Adds claims to access token if they are requested and auth request included non-null identity vector
Work done by @GHSwallow
=> Ato 1010/implement identity for token endpoint

src/components/config/tests/config-controller.test.ts, src/components/token/token-controller.ts, src/config.ts, src/types/access-token-store.ts, src/validators/user-info-request-validator.ts, tests/integration/user-info.test.ts
- We now have an in memory store for the access tokens we issue from the `/token` endpoint
- This is a key-value pair store where the key is `clientId.sub`
- We now store the tokens once we issue them in the token endpoint 
- I've added the same checks we do in the real `/userinfo` endpoint to see if the access token included in the request is in the store and matches
- Some very small renaming/refactoring in the last commit
- Code review commit by commit
=> ATO-1055 store access token

src/components/token/helper/create-id-token.ts, src/components/token/tests/helper/create-id-token.test.ts, src/components/utils/fake-signature.ts, src/components/utils/make-header-invalid.ts, src/components/utils/tests/fake-signature.test.ts, src/components/utils/tests/make-header-invalid.test.ts, src/constants.ts, tests/integration/token.test.ts
- Our token endpoint can now return invalid responses
- These can be configured after the work done here: https://github.com/govuk-one-login/simulator/pull/105
- This will allow RPs to test their error handling for the token endpoint
- Branches off https://github.com/govuk-one-login/simulator/pull/105, so must be merged first 🙂
=> ATO-1057 : Adds configured errors to ID token 

src/app.ts, src/components/openid-configuration/openid-configuration-controller.ts, src/components/trustmark/trustmark-controller.ts, src/config.ts, tests/integration/openid-configuration.test.ts, tests/integration/trustmark.test.ts
=> ATO-1018: Set up open id config & trustmark

src/parse/parse-token-request.ts, src/types/private-key-jwt.ts
BAU: Pulls the signing client assertion algorithm from the header not the client tokenSigningAlgorithm
=> BAU: fix client assertion signature check

src/components/user-info/user-info-controller.ts
The _jti_ fields is present in the vocab documentation, but is not sent in production.
=> BAU: Remove JTI From CoreIdentityJWT

src/components/user-info/user-info-controller.ts, tests/integration/helper/decode-jwt-no-verify.ts, tests/integration/token.test.ts, tests/integration/user-info.test.ts
- Added support for core identity error scenarios
- Factored out common _decodeJwtNoVerify_ helper
=> ATO-1058: Add Support For Core Identity Error Scenarios

src/parse/parse-token-request.ts, tests/integration/token.test.ts
Removes the unsupported ES keys from token request parser.
The error message has not been updated (ie still explains that ES keys are ok), as this is still the error message in OL.
=> ATO-1078: remove not supported signing keys

src/validators/tests/vtr-validator.test.ts, src/validators/vtr-validator.ts
- Due to a bug in the logic, the simulator would reject P0 with a low credential trust level as invalid. This is incorrect and the functionality has now been updated to correct this.
- Code review commit by commit 
- Look at the new test to ensure we've covered all the cases and fixed the bug
=> BAU: Fix VTR logic for P0 cases

tsconfig.json
TS was compiling the micro rp into the normal dist folder, which means the simulator was not compliled where node expected it to be
=> BAU: Fix tsconfig

README.md, src/app.ts, src/components/config/get-config-controller.ts, src/config.ts, tests/integration/get-config.test.ts
Adds a `get` for the `/config` endpoint, which returns the current configuration of the simulator. It returns 
- clientConfiguration
- errorConfiguration
- responseConfiguration
- simulatorUrl
in the body of the response.
it does not return
- authCodeRequestParamsStore
- accessTokenStore
=> ATO-1292: add get config endpoint

src/app.ts, src/components/authorise/authorise-get-controller.ts, src/components/form-submit/form-submit-controller.ts, src/components/utils/form/render-response-config-form.ts, src/types/auth-request-parameters.ts, tests/integration/authorise-get-controller.test.ts, tests/integration/form-submit-controller.test.ts
- Adds a new controller to handle the response config form submission 
- Modifies the form to include base64URL encoded auth request params to persist them between `/authorize` and form submission 
- Stores the submitted response configuration alongside the auth code when the form is submitted
- This allows us to store the form submitted response configuration alongside the auth request params, which allows us to persist this information when we're issuing access tokens and eventually the `/userinfo` response
-  Run the simulator in interactive mode and make an `/authorize` request. Upon clicking submit you should be redirected to the redirect_uri with an auth code
- To run this run: 
```
npm run build && INTERACTIVE_MODE=true npm run start
```
> [!NOTE]  
> Sonar thinks this introduces a …
=> ATO-1443: add controller to submit form

src/config.ts, src/parse/parse-auth-request.ts, src/parse/tests/parse-auth-request.test.ts, src/utils/utils.ts, src/validators/code-challenge-validator.ts, src/validators/tests/validate-auth-request-object.test.ts, src/validators/tests/validate-auth-request-query-params.test.ts, src/validators/validate-auth-request-object.ts, src/validators/validate-auth-request-query-params.ts, tests/integration/authorise-get-controller.test.ts
As part of supporting PKCE, we need to update the simulator to support PKCE behind a env variable.
Added PKCE support to the `/authorize` endpoint.
=> ATO-1379: support pkce in /authorize endpoint

src/parse/parse-auth-request.ts, src/parse/tests/parse-auth-request.test.ts, src/validators/tests/validate-auth-request-object.test.ts, src/validators/tests/validate-auth-request-query-params.test.ts, src/validators/validate-auth-request-object.ts, src/validators/validate-auth-request-query-params.ts, tests/integration/authorise-get-controller.test.ts
We are updating the main API to validate the response_mode field. We should add this to the simulator to match.
https://github.com/govuk-one-login/authentication-api/pull/6099
=> ATO-1020: validate response mode if present

src/components/token/token-controller.ts, tests/integration/token-controller.test.ts
The expires_in field represents the access token expiry in seconds[1]. Our access token is not valid for 3600 seconds, so this value was wrong
[1]- https://datatracker.ietf.org/doc/html/rfc6749#section-4.2.2
=> BAU: Fix expires_in field

CONTRIBUTING.md, README.md
It's not clear what in the README is intended for who. I've kept the readme as RP facing docs, and moved out the internal stuff. I've also added a couple of lines about external contributions
=> Split user and maintainer documentation

src/components/logout/logout-controller.ts, tests/integration/logout.test.ts
The actual logout endpoint does not do this validation and this is correct according to the spec[1]. JOSE does this by default but we can stop this by over-riding the current date to 0, therefore making all id_token_hints pass the exp validation.
[1]- https://openid.net/specs/openid-connect-rpinitiated-1_0.html#:~:text=When%20an%20id_token_hint,act%20upon%20it.
=> BAU: Don't validate the exp claim in id_token_hint

.github/workflows/run-acceptance-tests.yml
Context: A [dependabot update to the node version](https://github.com/govuk-one-login/simulator/pull/287) was merged. We want to ensure that the docker image will continue build and run correctly, without waiting for overnight acceptance tests.
- Allow acceptance tests to be triggered manually
=> ATO-1619 Enable manual trigger for acceptance tests

.env.template, .gitignore, CONTRIBUTING.md, acceptance-tests.docker-compose.yaml, run-acceptance-tests.sh
Adds a script to run all acceptance tests locally. The script will start containers for the simulator, selenium, and the micro RP images. 
The script uses environment variables defined in a file called `.env`. There is a template file (`.env.template`) that can be used to create this file. The variables must belong to an account that already exists in the build environment.
Also updates the docs to explain how to run the script.
=> BAU: Add script to run acceptance tests locally

Dockerfile
Bump node to patch vulnerabilities as per [changelog](https://github.com/nodejs/node/releases/tag/v22.15.1).
Tested by running docker locally and logging the version:
```
simulator  | 
simulator  | > simulator@1.0.0 start
simulator  | > node dist/server.js
simulator  | 
simulator  | Running Node.js version: v22.15.1
simulator  | {"level":30,"time":1747390789977,"pid":19,"hostname":"docker-desktop","msg":"[server]: Server is running at http://localhost:3000"}
```
=> BAU - Bump node to 22.15.1

src/config.ts, src/parse/parse-token-request.ts, src/parse/tests/parse-token-request.test.ts, tests/integration/token-controller.test.ts
Replicates: https://github.com/govuk-one-login/authentication-api/pull/6490
=> ATO-1566: Allow issuer as private_key_jwt_aud

src/constants.ts, src/parse/parse-auth-request.ts, src/validators/tests/validate-auth-request-object.test.ts, src/validators/tests/validate-auth-request-query-params.test.ts, src/validators/validate-auth-request-object.ts, src/validators/validate-auth-request-query-params.ts, tests/integration/authorise-get-controller.test.ts
Add channel validation to simulator. A valid channel is either null, web, or generic_app.
=> ATO-1694: add validation to channel claim

README.md
Context: The readme for Simulator points out that although Simulator mirrors One Login in most respects, Simulator doesn't include support for POST /authorize requests. But as we are now removing support for POST requests from One Login, this line can be removed from the Simulator readme.
- remove mention in the readme to not supporting POST /authorize requests.
=> ATO-1637: Remove reference to POST authorize requests

package-lock.json, package.json
Context: supertest depends on form-data which had a critical vulnerability. [A dependabot PR was approved](https://github.com/govuk-one-login/simulator/pull/324) to ensure that only the patched version of form-data was used.
- Update to the latest version of supertest, which uses the patched version of form-data.
- npm audit identified some further vulnerabilities (babel and brace-expansion) - `npm audit fix` applied here to ensure patched versions of these dependencies are used.
=> ATO-1861/Bump supertest and npm audit fix

acceptance-tests-local.docker-compose.yaml, src/components/token/tests/helper/create-id-token.test.ts, src/components/utils/make-header-invalid.ts, src/components/utils/tests/make-header-invalid.test.ts, tests/integration/token-controller.test.ts
This PR adds a `kid` field to the header of the ID token sent when the `INVALID_ALG_HEADER` error is enabled in the simulator (resolves https://github.com/govuk-one-login/simulator/issues/323)
=> ATO-1855: Add `kid` to header of `INVALID_ALG_HEADER` id token

.eslintignore, .eslintrc.json
The use of the`.eslintignore` file is deprecated in a version we'd like to update to, so i've moved this into the `.eslintrc` config file.
=> BAU: Move .eslintignores into .eslintrc.json

src/components/user-info/user-info-controller.ts, src/components/utils/make-header-invalid.ts, tests/integration/user-info.test.ts
Resolves https://github.com/govuk-one-login/simulator/issues/342
Also adds unit test coverage for this
=> ATO-1951: Add missing did controller id to header in INVALID_ALG_HEADER response

.github/workflows/pre-merge-and-main-checks.yml, .github/workflows/run-acceptance-tests.yml, .npmrc, Dockerfile, tests/acceptance/micro-rp/Dockerfile
Adds a few things to improve the way we manage dependencies, namely:
- Use `npm ci` in CI/CD infra and Dockerfiles to ensure builds respect the lockfile 
- Omit dev dependencies from the final image
-  Add an .npmrc file which has the `ignore-scripts=true` to ensure we ignore any lifecycle scripts from pulled in dependencies
=> BAU: Improve dependency management  

package-lock.json, package.json, src/components/form-submit/form-submit-controller.ts, src/components/logout/logout-controller.ts, src/parse/parse-token-request.ts, src/validators/signed-jwt-validator.ts
- Pino versions prior to 9.12.0 were depending on `fast-redact`, which was vulnerable to prototype pollution (https://github.com/govuk-one-login/simulator/security/dependabot/16). 
- [Pino v9.12.0](https://github.com/pinojs/pino/releases/tag/v9.12.0) replaces `fast-redact` with `slow-redact`, so i've set this as the minimum version
=> BAU: Update minimum pino version
